---
# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json

# The version of the configuration file format.
version: '0.2'
# The locale to use when spell checking. (e.g., en, en-GB, de-DE
language: en,vi
cache:
  cacheFormat: universal
  cacheStrategy: metadata
  useCache: true
dictionaryDefinitions:
  - path: ./app/assets/dictionary.txt
    name: custom-dictionary

dictionaries:
  - custom-dictionary
